FROM openjdk:8-jre-alpine

COPY target/Afgangsprojekt-1.0-SNAPSHOT-jar-with-dependencies.jar /Afgangsprojekt-1.0-SNAPSHOT-jar-with-dependencies.jar

CMD ["java","-jar", "Afgangsprojekt-1.0-SNAPSHOT-jar-with-dependencies.jar"]

